#!/bin/bash
set -e

pacman -Syu --noconfirm \
	rxvt-unicode-terminfo bash-completion btrfs-progs jq cockpit-dashboard packagekit udisks2

# use external disk for blockchain data
DISK=/dev/sdc # TODO detect in a smart way
mkfs.btrfs -f -L data $DISK
mount $DISK /mnt
btrfs subvolume create /mnt/chain

# enable mount 
cat <<EOF > /etc/systemd/system/var-lib-chain.mount
[Unit]
Description=Chain data

[Mount]
What=$DISK
Where=/var/lib/chain
Type=btrfs
Options=subvol=chain

[Install]
WantedBy=multi-user.target
EOF

cat <<\EOF > /usr/local/bin/node_update
#!/bin/bash
set -e
repo=${1:-valibre-org/node}
json=`curl -fsL https://api.github.com/repos/$repo/releases/latest`
url=`echo $json | jq -r '.assets[0].browser_download_url'`
ver=`echo $json | jq -r .tag_name`
dest=/usr/local/bin/node-$ver
curl -fsL $url > $dest
chmod +x $dest
ln -sf $dest /usr/local/bin/node
EOF
chmod +x /usr/local/bin/node_update

cat <<EOF > /etc/systemd/system/node.service
[Unit]
Description=Blockchain node
After=network.target var-lib-chain.mount

[Service]
Type=simple
ExecStart=/usr/local/bin/node --base-path /var/lib/chain --dev --ws-port 80 --ws-external
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

node_update
systemctl daemon-reload
systemctl enable var-lib-chain.mount
systemctl enable node
systemctl start var-lib-chain.mount
systemctl start node
sudo systemctl enable --now cockpit.socket

